### ISSUE TITLE
Error: Default condition should be last one

### ISSUE THREAD

**Issue by dml0031** [takagiy/validated-extendable.js#2]
Unable to import package without receiving this error:

<img width="930" alt="Screenshot 2024-07-16 at 12 47 27 PM" src="https://github.com/user-attachments/assets/43a99f35-96e4-4a3c-a216-d19928de18d1">

**Comment by takagiy** [comment]
@dml0031 
Thank you for reporting!
I've published `v7.0.1` to fix this. Can you try the latest version?

**Comment by dml0031** [comment]
> @dml0031 Thank you for reporting! I've published ~`v7.0.1`~ `v7.0.2` to fix this. Can you try the latest version?

That appears to have fixed it!
