### ISSUE TITLE
Unable to call class methods

### ISSUE THREAD

**Issue by dml0031** [takagiy/validated-extendable.js#3]
Take example:

```
class Person extends Validated(schema) {
  input() {
   return this.name
  }
}

new Person({ name: "test" }).input()
```
It just returns an error that says `TypeError: (intermediate value).input is not a function`

Any help on this would be great!

**Comment by takagiy** [comment]
@dml0031
I can't believe I missed this until you reported it to me. I really appreciate you.

Thanks to you, I think I've fixed the issue and now the class method should work.

**Comment by dml0031** [comment]
Appreciate your response and quick fix! Thank you. Appears to be all good now!
